#This layout inspired by popular fantasy games
title:
  x: 75
  y: 75
  width: 500
  height: 50

upper_right:
  x: 595
  y: 75
  width: 135
  height: 50
  align: right
ur: # alias
  extends: upper_right

art:
  x: 75
  y: 130
  width: 675
  height: 520

type:
  x: 90
  y: 675
  width: 500
  height: 50

type_right:
  x: 595
  y: 675
  width: 135
  height: 50
  align: right
tr: #alias
  extends: type_right

description:
  x: 75
  y: 730
  width: 675
  height: 320
  valign: middle
  align: center
  font_size: 18
desc: # alias
  extends: description

vp_effect:
  x: 75
  y: 660
  width: 675
  height: 120
  align: right
  font_size: 36

special_effect:
#75 + 84
  x: 162 
  y: 740
  width: 675
  height: 120
  align: left
  valign: bottom
  font_size: 36



#84x84 blocks 8 across, 3 down with gaps
#vertical offset is 106
descR1C1:
  y: 755
  x: 75
  width: 84
  height: 84

#<?php
#for($r = 0; $r <3; $r++){
#       for($c =0; $c < 8; $c++){
# 	      echo "
#descR" . ($r+1) . "C" . ($c+1) . ":
#  extends: descR1C1 
#  x: += ". 84*$c ."
#  y: += ". 106*$r ."
#";
#	}
#}

descR1C2:
  extends: descR1C1 
  x: += 84
  y: += 0

descR1C3:
  extends: descR1C1 
  x: += 168
  y: += 0

descR1C4:
  extends: descR1C1 
  x: += 252
  y: += 0

descR1C5:
  extends: descR1C1 
  x: += 336
  y: += 0

descR1C6:
  extends: descR1C1 
  x: += 420
  y: += 0

descR1C7:
  extends: descR1C1 
  x: += 504
  y: += 0

descR1C8:
  extends: descR1C1 
  x: += 588
  y: += 0

descR2C1:
  extends: descR1C1 
  x: += 0
  y: += 106

descR2C2:
  extends: descR1C1 
  x: += 84
  y: += 106

descR2C3:
  extends: descR1C1 
  x: += 168
  y: += 106

descR2C4:
  extends: descR1C1 
  x: += 252
  y: += 106

descR2C5:
  extends: descR1C1 
  x: += 336
  y: += 106

descR2C6:
  extends: descR1C1 
  x: += 420
  y: += 106

descR2C7:
  extends: descR1C1 
  x: += 504
  y: += 106

descR2C8:
  extends: descR1C1 
  x: += 588
  y: += 106

descR3C1:
  extends: descR1C1 
  x: += 0
  y: += 212

descR3C2:
  extends: descR1C1 
  x: += 84
  y: += 212

descR3C3:
  extends: descR1C1 
  x: += 168
  y: += 212

descR3C4:
  extends: descR1C1 
  x: += 252
  y: += 212

descR3C5:
  extends: descR1C1 
  x: += 336
  y: += 212

descR3C6:
  extends: descR1C1 
  x: += 420
  y: += 212

descR3C7:
  extends: descR1C1 
  x: += 504
  y: += 212

descR3C8:
  extends: descR1C1 
  x: += 588
  y: += 212


#Some extra wide versions for columns that get 2 digit numbers
descR1C7special:
  extends: descR1C7 
  x: -= 5
  width: += 25
  
descR2C1special:
  extends: descR2C1 
  x: -= 5
  width: += 25

descR3C1special:
  extends: descR3C1 
  x: -= 5
  width: += 25


lower_right:
  x: 675
  y: 975
  width: 75
  height: 75
  font_size: 18
  valign: bottom
  align: right
lr: #alias
  extends: lower_right

lower_left:
  x: 75
  y: 975
  width: 75
  height: 75
  font_size: 18
  valign: bottom
  align: left
ll: # alias
  extends: lower_left

copyright:
  x: 75
  y: 1025
  width: 675
  height: 25
  font_size: 16
  align: center
  valign: bottom
#aliases for copyright
copy:
  extends: copyright
credit:
  extends: copyright
credits:
  extends: copyright

# The "cut line", without rounded corners
cut:
  x: 37.5
  y: 37.5
  width: 750
  height: 1050

# The "safe zone" as defined by TheGameCrafter poker cards
safe:
  x: 75
  y: 75
  width: 675
  height: 975
  radius: 16
  dash: 3 3
